/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RemsApi);
  }
}(this, function(expect, RemsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RemsApi.RealtyApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RealtyApi', function() {
    describe('deleteFavorite', function() {
      it('should call deleteFavorite successfully', function(done) {
        //uncomment below and update the code to test deleteFavorite
        //instance.deleteFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteKeyword', function() {
      it('should call deleteKeyword successfully', function(done) {
        //uncomment below and update the code to test deleteKeyword
        //instance.deleteKeyword(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listFavorite', function() {
      it('should call listFavorite successfully', function(done) {
        //uncomment below and update the code to test listFavorite
        //instance.listFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listKeyword', function() {
      it('should call listKeyword successfully', function(done) {
        //uncomment below and update the code to test listKeyword
        //instance.listKeyword(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listRealty', function() {
      it('should call listRealty successfully', function(done) {
        //uncomment below and update the code to test listRealty
        //instance.listRealty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mapRealty', function() {
      it('should call mapRealty successfully', function(done) {
        //uncomment below and update the code to test mapRealty
        //instance.mapRealty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postFavorite', function() {
      it('should call postFavorite successfully', function(done) {
        //uncomment below and update the code to test postFavorite
        //instance.postFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postRealty', function() {
      it('should call postRealty successfully', function(done) {
        //uncomment below and update the code to test postRealty
        //instance.postRealty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('viewRealty', function() {
      it('should call viewRealty successfully', function(done) {
        //uncomment below and update the code to test viewRealty
        //instance.viewRealty(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
