/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RemsApi);
  }
}(this, function(expect, RemsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RemsApi.ListOption();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListOption', function() {
    it('should create an instance of ListOption', function() {
      // uncomment below and update the code to test ListOption
      //var instane = new RemsApi.ListOption();
      //expect(instance).to.be.a(RemsApi.ListOption);
    });

    it('should have the property utility (base name: "utility")', function() {
      // uncomment below and update the code to test the property utility
      //var instane = new RemsApi.ListOption();
      //expect(instance).to.be();
    });

    it('should have the property projectType (base name: "project_type")', function() {
      // uncomment below and update the code to test the property projectType
      //var instane = new RemsApi.ListOption();
      //expect(instance).to.be();
    });

    it('should have the property realtyType (base name: "realty_type")', function() {
      // uncomment below and update the code to test the property realtyType
      //var instane = new RemsApi.ListOption();
      //expect(instance).to.be();
    });

    it('should have the property method (base name: "method")', function() {
      // uncomment below and update the code to test the property method
      //var instane = new RemsApi.ListOption();
      //expect(instance).to.be();
    });

    it('should have the property direction (base name: "direction")', function() {
      // uncomment below and update the code to test the property direction
      //var instane = new RemsApi.ListOption();
      //expect(instance).to.be();
    });

    it('should have the property priceUnit (base name: "price_unit")', function() {
      // uncomment below and update the code to test the property priceUnit
      //var instane = new RemsApi.ListOption();
      //expect(instance).to.be();
    });

  });

}));
