/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RemsApi);
  }
}(this, function(expect, RemsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RemsApi.RealtyKeyword();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RealtyKeyword', function() {
    it('should create an instance of RealtyKeyword', function() {
      // uncomment below and update the code to test RealtyKeyword
      //var instane = new RemsApi.RealtyKeyword();
      //expect(instance).to.be.a(RemsApi.RealtyKeyword);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new RemsApi.RealtyKeyword();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new RemsApi.RealtyKeyword();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new RemsApi.RealtyKeyword();
      //expect(instance).to.be();
    });

    it('should have the property thumbMap (base name: "thumb_map")', function() {
      // uncomment below and update the code to test the property thumbMap
      //var instane = new RemsApi.RealtyKeyword();
      //expect(instance).to.be();
    });

    it('should have the property coordinate (base name: "coordinate")', function() {
      // uncomment below and update the code to test the property coordinate
      //var instane = new RemsApi.RealtyKeyword();
      //expect(instance).to.be();
    });

  });

}));
