/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RemsApi);
  }
}(this, function(expect, RemsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new RemsApi.RealtyList();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RealtyList', function() {
    it('should create an instance of RealtyList', function() {
      // uncomment below and update the code to test RealtyList
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be.a(RemsApi.RealtyList);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

    it('should have the property priceUnit (base name: "price_unit")', function() {
      // uncomment below and update the code to test the property priceUnit
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

    it('should have the property thumb (base name: "thumb")', function() {
      // uncomment below and update the code to test the property thumb
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

    it('should have the property ward (base name: "ward")', function() {
      // uncomment below and update the code to test the property ward
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

    it('should have the property district (base name: "district")', function() {
      // uncomment below and update the code to test the property district
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

    it('should have the property isFavorite (base name: "is_favorite")', function() {
      // uncomment below and update the code to test the property isFavorite
      //var instane = new RemsApi.RealtyList();
      //expect(instance).to.be();
    });

  });

}));
