/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Feedback', 'model/GenericError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Feedback'), require('../model/GenericError'));
  } else {
    // Browser globals (root is window)
    if (!root.RemsApi) {
      root.RemsApi = {};
    }
    root.RemsApi.FeedbackApi = factory(root.RemsApi.ApiClient, root.RemsApi.Feedback, root.RemsApi.GenericError);
  }
}(this, function(ApiClient, Feedback, GenericError) {
  'use strict';

  /**
   * Feedback service.
   * @module api/FeedbackApi
   * @version 1.0.0
   */

  /**
   * Constructs a new FeedbackApi. 
   * @alias module:api/FeedbackApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the postFeedback operation.
     * @callback module:api/FeedbackApi~postFeedbackCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Feedback} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {module:model/Feedback} opts.body 
     * @param {module:api/FeedbackApi~postFeedbackCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Feedback}
     */
    this.postFeedback = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['body'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Feedback;

      return this.apiClient.callApi(
        '/feedback', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
