/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GenericError', 'model/Setting'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GenericError'), require('../model/Setting'));
  } else {
    // Browser globals (root is window)
    if (!root.RemsApi) {
      root.RemsApi = {};
    }
    root.RemsApi.SettingApi = factory(root.RemsApi.ApiClient, root.RemsApi.GenericError, root.RemsApi.Setting);
  }
}(this, function(ApiClient, GenericError, Setting) {
  'use strict';

  /**
   * Setting service.
   * @module api/SettingApi
   * @version 1.0.0
   */

  /**
   * Constructs a new SettingApi. 
   * @alias module:api/SettingApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the changeLanguage operation.
     * @callback module:api/SettingApi~changeLanguageCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Setting} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} lang 
     * @param {module:api/SettingApi~changeLanguageCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Setting}
     */
    this.changeLanguage = function(lang, callback) {
      var postBody = null;

      // verify the required parameter 'lang' is set
      if (lang === undefined || lang === null) {
        throw new Error("Missing the required parameter 'lang' when calling changeLanguage");
      }


      var pathParams = {
        'lang': lang
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Bearer'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Setting;

      return this.apiClient.callApi(
        '/setting/language/{lang}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
