/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/City', 'model/District', 'model/Ward'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./City'), require('./District'), require('./Ward'));
  } else {
    // Browser globals (root is window)
    if (!root.RemsApi) {
      root.RemsApi = {};
    }
    root.RemsApi.ListCity = factory(root.RemsApi.ApiClient, root.RemsApi.City, root.RemsApi.District, root.RemsApi.Ward);
  }
}(this, function(ApiClient, City, District, Ward) {
  'use strict';




  /**
   * The ListCity model module.
   * @module model/ListCity
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ListCity</code>.
   * @alias module:model/ListCity
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>ListCity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ListCity} obj Optional instance to populate.
   * @return {module:model/ListCity} The populated <code>ListCity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('city')) {
        obj['city'] = City.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('district')) {
        obj['district'] = District.constructFromObject(data['district']);
      }
      if (data.hasOwnProperty('ward')) {
        obj['ward'] = Ward.constructFromObject(data['ward']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/City} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {module:model/District} district
   */
  exports.prototype['district'] = undefined;
  /**
   * @member {module:model/Ward} ward
   */
  exports.prototype['ward'] = undefined;



  return exports;
}));


