/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Coordinate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Coordinate'));
  } else {
    // Browser globals (root is window)
    if (!root.RemsApi) {
      root.RemsApi = {};
    }
    root.RemsApi.RealtyKeyword = factory(root.RemsApi.ApiClient, root.RemsApi.Coordinate);
  }
}(this, function(ApiClient, Coordinate) {
  'use strict';




  /**
   * The RealtyKeyword model module.
   * @module model/RealtyKeyword
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RealtyKeyword</code>.
   * @alias module:model/RealtyKeyword
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>RealtyKeyword</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RealtyKeyword} obj Optional instance to populate.
   * @return {module:model/RealtyKeyword} The populated <code>RealtyKeyword</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('thumb_map')) {
        obj['thumb_map'] = ApiClient.convertToType(data['thumb_map'], 'String');
      }
      if (data.hasOwnProperty('filter')) {
        obj['filter'] = ApiClient.convertToType(data['filter'], 'String');
      }
      if (data.hasOwnProperty('coordinate')) {
        obj['coordinate'] = Coordinate.constructFromObject(data['coordinate']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {String} thumb_map
   */
  exports.prototype['thumb_map'] = undefined;
  /**
   * @member {String} filter
   */
  exports.prototype['filter'] = undefined;
  /**
   * @member {module:model/Coordinate} coordinate
   */
  exports.prototype['coordinate'] = undefined;



  return exports;
}));


