/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/City', 'model/District', 'model/Ward'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./City'), require('./District'), require('./Ward'));
  } else {
    // Browser globals (root is window)
    if (!root.RemsApi) {
      root.RemsApi = {};
    }
    root.RemsApi.RealtyList = factory(root.RemsApi.ApiClient, root.RemsApi.City, root.RemsApi.District, root.RemsApi.Ward);
  }
}(this, function(ApiClient, City, District, Ward) {
  'use strict';




  /**
   * The RealtyList model module.
   * @module model/RealtyList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RealtyList</code>.
   * @alias module:model/RealtyList
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>RealtyList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RealtyList} obj Optional instance to populate.
   * @return {module:model/RealtyList} The populated <code>RealtyList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('price_unit')) {
        obj['price_unit'] = ApiClient.convertToType(data['price_unit'], 'Number');
      }
      if (data.hasOwnProperty('thumb')) {
        obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('ward')) {
        obj['ward'] = Ward.constructFromObject(data['ward']);
      }
      if (data.hasOwnProperty('district')) {
        obj['district'] = District.constructFromObject(data['district']);
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = City.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('is_favorite')) {
        obj['is_favorite'] = ApiClient.convertToType(data['is_favorite'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {Number} price_unit
   */
  exports.prototype['price_unit'] = undefined;
  /**
   * @member {String} thumb
   */
  exports.prototype['thumb'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {module:model/Ward} ward
   */
  exports.prototype['ward'] = undefined;
  /**
   * @member {module:model/District} district
   */
  exports.prototype['district'] = undefined;
  /**
   * @member {module:model/City} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {Number} is_favorite
   */
  exports.prototype['is_favorite'] = undefined;



  return exports;
}));


