/**
 * REMS API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/City', 'model/Coordinate', 'model/District', 'model/Utility', 'model/Ward'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./City'), require('./Coordinate'), require('./District'), require('./Utility'), require('./Ward'));
  } else {
    // Browser globals (root is window)
    if (!root.RemsApi) {
      root.RemsApi = {};
    }
    root.RemsApi.Realty = factory(root.RemsApi.ApiClient, root.RemsApi.City, root.RemsApi.Coordinate, root.RemsApi.District, root.RemsApi.Utility, root.RemsApi.Ward);
  }
}(this, function(ApiClient, City, Coordinate, District, Utility, Ward) {
  'use strict';




  /**
   * The Realty model module.
   * @module model/Realty
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Realty</code>.
   * @alias module:model/Realty
   * @class
   * @param authorId {Number} 
   * @param title {String} 
   * @param method {String} 
   * @param typeId {Number} 
   * @param address {String} 
   */
  var exports = function(authorId, title, method, typeId, address) {
    var _this = this;


    _this['author_id'] = authorId;
    _this['title'] = title;










    _this['method'] = method;
    _this['type_id'] = typeId;














    _this['address'] = address;
















<<<<<<< HEAD

=======
>>>>>>> aa6b38c0e952985dccf2be02732b7d2ee1e7738f
  };

  /**
   * Constructs a <code>Realty</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Realty} obj Optional instance to populate.
   * @return {module:model/Realty} The populated <code>Realty</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('author_id')) {
        obj['author_id'] = ApiClient.convertToType(data['author_id'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('project_id')) {
        obj['project_id'] = ApiClient.convertToType(data['project_id'], 'Number');
      }
      if (data.hasOwnProperty('excerpt')) {
        obj['excerpt'] = ApiClient.convertToType(data['excerpt'], 'String');
      }
      if (data.hasOwnProperty('body')) {
        obj['body'] = ApiClient.convertToType(data['body'], 'String');
      }
      if (data.hasOwnProperty('thumb')) {
        obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
      }
      if (data.hasOwnProperty('thumb_map')) {
        obj['thumb_map'] = ApiClient.convertToType(data['thumb_map'], 'String');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ApiClient.convertToType(data['image'], ['String']);
      }
      if (data.hasOwnProperty('featured')) {
        obj['featured'] = ApiClient.convertToType(data['featured'], 'Number');
      }
      if (data.hasOwnProperty('start_date')) {
        obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Number');
      }
      if (data.hasOwnProperty('end_date')) {
        obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Number');
      }
      if (data.hasOwnProperty('method')) {
        obj['method'] = ApiClient.convertToType(data['method'], 'String');
      }
      if (data.hasOwnProperty('type_id')) {
        obj['type_id'] = ApiClient.convertToType(data['type_id'], 'Number');
      }
      if (data.hasOwnProperty('area')) {
        obj['area'] = ApiClient.convertToType(data['area'], 'Number');
      }
      if (data.hasOwnProperty('area_build')) {
        obj['area_build'] = ApiClient.convertToType(data['area_build'], 'Number');
      }
      if (data.hasOwnProperty('toilet')) {
        obj['toilet'] = ApiClient.convertToType(data['toilet'], 'Number');
      }
      if (data.hasOwnProperty('bedroom')) {
        obj['bedroom'] = ApiClient.convertToType(data['bedroom'], 'Number');
      }
      if (data.hasOwnProperty('bathroom')) {
        obj['bathroom'] = ApiClient.convertToType(data['bathroom'], 'Number');
      }
      if (data.hasOwnProperty('direction')) {
        obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
      }
      if (data.hasOwnProperty('floor')) {
        obj['floor'] = ApiClient.convertToType(data['floor'], 'Number');
      }
      if (data.hasOwnProperty('road')) {
        obj['road'] = ApiClient.convertToType(data['road'], 'Number');
      }
      if (data.hasOwnProperty('front')) {
        obj['front'] = ApiClient.convertToType(data['front'], 'Number');
      }
      if (data.hasOwnProperty('length')) {
        obj['length'] = ApiClient.convertToType(data['length'], 'Number');
      }
      if (data.hasOwnProperty('width')) {
        obj['width'] = ApiClient.convertToType(data['width'], 'Number');
      }
      if (data.hasOwnProperty('rear_hatch')) {
        obj['rear_hatch'] = ApiClient.convertToType(data['rear_hatch'], 'Boolean');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'Number');
      }
      if (data.hasOwnProperty('price_unit')) {
        obj['price_unit'] = ApiClient.convertToType(data['price_unit'], 'Number');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('ward_id')) {
        obj['ward_id'] = ApiClient.convertToType(data['ward_id'], 'Number');
      }
      if (data.hasOwnProperty('district_id')) {
        obj['district_id'] = ApiClient.convertToType(data['district_id'], 'Number');
      }
      if (data.hasOwnProperty('city_id')) {
        obj['city_id'] = ApiClient.convertToType(data['city_id'], 'Number');
      }
      if (data.hasOwnProperty('ward')) {
        obj['ward'] = Ward.constructFromObject(data['ward']);
      }
      if (data.hasOwnProperty('district')) {
        obj['district'] = District.constructFromObject(data['district']);
      }
      if (data.hasOwnProperty('city')) {
        obj['city'] = City.constructFromObject(data['city']);
      }
      if (data.hasOwnProperty('coordinate')) {
        obj['coordinate'] = Coordinate.constructFromObject(data['coordinate']);
      }
      if (data.hasOwnProperty('contact_name')) {
        obj['contact_name'] = ApiClient.convertToType(data['contact_name'], 'String');
      }
      if (data.hasOwnProperty('contact_address')) {
        obj['contact_address'] = ApiClient.convertToType(data['contact_address'], 'String');
      }
      if (data.hasOwnProperty('contact_phone')) {
        obj['contact_phone'] = ApiClient.convertToType(data['contact_phone'], 'String');
      }
      if (data.hasOwnProperty('contact_email')) {
        obj['contact_email'] = ApiClient.convertToType(data['contact_email'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
      }
      if (data.hasOwnProperty('is_favorite')) {
        obj['is_favorite'] = ApiClient.convertToType(data['is_favorite'], 'Number');
      }
      if (data.hasOwnProperty('utility')) {
        obj['utility'] = Utility.constructFromObject(data['utility']);
      }
      if (data.hasOwnProperty('video')) {
        obj['video'] = ApiClient.convertToType(data['video'], 'String');
      }
      if (data.hasOwnProperty('link_share')) {
        obj['link_share'] = ApiClient.convertToType(data['link_share'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} author_id
   */
  exports.prototype['author_id'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {String} code
   */
  exports.prototype['code'] = undefined;
  /**
   * @member {Number} project_id
   */
  exports.prototype['project_id'] = undefined;
  /**
   * @member {String} excerpt
   */
  exports.prototype['excerpt'] = undefined;
  /**
   * @member {String} body
   */
  exports.prototype['body'] = undefined;
  /**
   * @member {String} thumb
   */
  exports.prototype['thumb'] = undefined;
  /**
   * @member {String} thumb_map
   */
  exports.prototype['thumb_map'] = undefined;
  /**
   * @member {Array.<String>} image
   */
  exports.prototype['image'] = undefined;
  /**
   * @member {Number} featured
   */
  exports.prototype['featured'] = undefined;
  /**
   * @member {Number} start_date
   */
  exports.prototype['start_date'] = undefined;
  /**
   * @member {Number} end_date
   */
  exports.prototype['end_date'] = undefined;
  /**
   * @member {String} method
   */
  exports.prototype['method'] = undefined;
  /**
   * @member {Number} type_id
   */
  exports.prototype['type_id'] = undefined;
  /**
   * @member {Number} area
   */
  exports.prototype['area'] = undefined;
  /**
   * @member {Number} area_build
   */
  exports.prototype['area_build'] = undefined;
  /**
   * @member {Number} toilet
   */
  exports.prototype['toilet'] = undefined;
  /**
   * @member {Number} bedroom
   */
  exports.prototype['bedroom'] = undefined;
  /**
   * @member {Number} bathroom
   */
  exports.prototype['bathroom'] = undefined;
  /**
   * @member {String} direction
   */
  exports.prototype['direction'] = undefined;
  /**
   * @member {Number} floor
   */
  exports.prototype['floor'] = undefined;
  /**
   * @member {Number} road
   */
  exports.prototype['road'] = undefined;
  /**
   * @member {Number} front
   */
  exports.prototype['front'] = undefined;
  /**
   * @member {Number} length
   */
  exports.prototype['length'] = undefined;
  /**
   * @member {Number} width
   */
  exports.prototype['width'] = undefined;
  /**
   * @member {Boolean} rear_hatch
   */
  exports.prototype['rear_hatch'] = undefined;
  /**
   * @member {Number} price
   */
  exports.prototype['price'] = undefined;
  /**
   * @member {Number} price_unit
   */
  exports.prototype['price_unit'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {Number} ward_id
   */
  exports.prototype['ward_id'] = undefined;
  /**
   * @member {Number} district_id
   */
  exports.prototype['district_id'] = undefined;
  /**
   * @member {Number} city_id
   */
  exports.prototype['city_id'] = undefined;
  /**
   * @member {module:model/Ward} ward
   */
  exports.prototype['ward'] = undefined;
  /**
   * @member {module:model/District} district
   */
  exports.prototype['district'] = undefined;
  /**
   * @member {module:model/City} city
   */
  exports.prototype['city'] = undefined;
  /**
   * @member {module:model/Coordinate} coordinate
   */
  exports.prototype['coordinate'] = undefined;
  /**
   * @member {String} contact_name
   */
  exports.prototype['contact_name'] = undefined;
  /**
   * @member {String} contact_address
   */
  exports.prototype['contact_address'] = undefined;
  /**
   * @member {String} contact_phone
   */
  exports.prototype['contact_phone'] = undefined;
  /**
   * @member {String} contact_email
   */
  exports.prototype['contact_email'] = undefined;
  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} updated_at
   */
  exports.prototype['updated_at'] = undefined;
  /**
   * @member {Number} is_favorite
   */
  exports.prototype['is_favorite'] = undefined;
  /**
   * @member {module:model/Utility} utility
   */
  exports.prototype['utility'] = undefined;
  /**
   * @member {String} video
   */
  exports.prototype['video'] = undefined;
  /**
   * @member {String} link_share
   */
  exports.prototype['link_share'] = undefined;



  return exports;
}));


