import LocalizedStrings from 'react-native-localization';
import setLanguage from './setLanguage';

const strings = new LocalizedStrings({
  eng: {
    close: 'Close',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    searchLabel: 'Search',
    historyLabel: 'History',
    historyTitle: 'Saved Searches',
    favoriteLabel: 'Favorite',
    favoriteTitle: 'Favorite Saved',
    profileLabel: 'Profile',
    profileTitle: 'Profile',
    menuLabel: 'Menu',
    menuTitle: 'Menu',
    filter: 'Filter',
    searchCityPlaceholder: 'Search address',
    customer: 'Customer',
    agency: 'Agency',
    sortScreen: 'Sort',
    filterScreen: 'Filters',
    additionalInformation: 'Edit account',
    changePassword: 'Change password',
    loginScreen: 'Login',
    registerScreen: 'Register',
    forgotScreen: 'Forgot',
    listProject: 'List Project',
    listAgency: 'List Agency',
    agencyDetail: 'Agency detail',
    settings: 'Settings',
    feedback: 'Feedback',
    createRealty: 'Create realty',
    listContact: 'List contact',
    agencyProject: 'All projects',
    postRealty: 'Post new realty'
  },
  vni: {
    close: 'Huỷ',
    back: 'Quay lại',
    save: 'Lưu',
    cancel: 'Huỷ',
    delete: 'Xoá',
    searchLabel: 'Tìm kiếm',
    historyLabel: 'Đã tìm',
    historyTitle: 'BĐS đã tìm',
    favoriteLabel: 'Yêu thích',
    favoriteTitle: 'BĐS yêu thích',
    profileLabel: 'Tài khoản',
    profileTitle: 'Tài khoản',
    menuLabel: 'Menu',
    menuTitle: 'Menu',
    filter: 'Lọc',
    searchCityPlaceholder: 'Tìm kiếm theo địa chỉ',
    customer: 'Khách hàng',
    agency: 'Nhà môi giới',
    sortScreen: 'Sắp xếp',
    filterScreen: 'Lọc',
    additionalInformation: 'Chỉnh sửa tài khoản',
    changePassword: 'Thay đổi mật khẩu',
    loginScreen: 'Đăng nhập',
    registerScreen: 'Đăng ký',
    forgotScreen: 'Quên mật khẩu',
    listProject: 'Danh sách dự án',
    listAgency: 'Danh sách nhà môi giới',
    agencyDetail: 'Chi tiết nhà môi giới',
    settings: 'Cài đặt',
    feedback: 'Phản hồi',
    createRealty: 'Đăng tin BĐS',
    listContact: 'Danh sách liên hệ',
    agencyProject: 'Tất cả dự án',
    postRealty: 'Đăng tin BĐS'
  }
});

setLanguage(strings);
module.exports = strings;
